import type { Metadata } from "next";
import { Caveat, JetBrains_Mono, Manrope } from "next/font/google";
import "./globals.css";
import LenisScroll from "@/components/shared/Lenis";
import { ClerkProvider } from "@clerk/nextjs";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const jetBrains = JetBrains_Mono({
  variable: "--font-jetBrains",
  subsets: ["latin"],
});
const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.variable} ${jetBrains.variable} ${caveat.variable} antialiased`}>
          {children}
          <LenisScroll />
        </body>
      </html>
    </ClerkProvider>
  );
}
